[package]
name = "diffuse"
version = "3.0.1"
description = "A music player that connects to your cloud/distributed storage"
authors = ["you"]
license = ""
repository = ""
default-run = "diffuse"
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { git = "https://github.com/tauri-apps/tauri/", branch = "next" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["api-all"] }
tauri-plugin-localhost = { git = "https://github.com/tauri-apps/tauri-plugin-localhost.git", branch = "release" }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
