env:
  browser: true
  es6: true
  worker: true

extends:
  eslint:recommended

parserOptions:
  ecmaVersion: 2018
  sourceType: module

globals:
  Elm: readonly
  MediaMetadata: readonly
  RemoteStorage: readonly
  tocca: readonly

rules:
  no-cond-assign:
    0

  no-unexpected-multiline:
    0

  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
